[package]
name = "bufread"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.5"
rand = "0.8.5"

[[bench]]
name = "buffer_benches"
harness = false

[[bench]]
name = "reader_benches"
harness = false
